// <auto-generated />
namespace CarPartsStore__License_App_.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ImageFieldAddedtoManufactures : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ImageFieldAddedtoManufactures));
        
        string IMigrationMetadata.Id
        {
            get { return "201806181525480_ImageFieldAddedtoManufactures"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
